fix(examples/snake): Fix build - use of undefined identifier
Before this change, the following command:

```
cd examples
dub build -c game1
```

failed with:

```
...
Building bindbc-sdl-examples ~master: building configuration [game1]
game/snake.d(213,51): Error: undefined identifier `alphaOpaque` in package `sdl`
game/snake.d(222,58): Error: undefined identifier `alphaOpaque` in package `sdl`
game/snake.d(224,56): Error: undefined identifier `alphaOpaque` in package `sdl`
game/snake.d(228,55): Error: undefined identifier `alphaOpaque` in package `sdl`
```

The `sdl.pixels` module contains a number of `makeEnumBind` mixin
invocations, however, `SDL_ALPHA_OPAQUE` is defined as an `enum`
directly, without using `bindbc.sdl.codegen`.

So, use the `SDL_ALPHA_OPAQUE` manifest constant directly.