fix(sdl.surface): Avoid duplicate symbol warning/error
Before this change, running `dub --root examples/ build -c game1`
produced the following warnings during linking:
```
...
Linking bindbc-sdl-examples
ld: warning: duplicate symbol '_SDL_GetRGBA' in:
    ../../../../.dub/cache/bindbc-sdl/~master/build/dynamic-debug-WtMyvUIt1hTP35kVNTgyxA/libBindBC_SDL.a(sdl.pixels.o)
    ../../../../.dub/cache/bindbc-sdl/~master/build/dynamic-debug-WtMyvUIt1hTP35kVNTgyxA/libBindBC_SDL.a(sdl.surface.o)
```

In a personal project of mine, these linker warnings actually manifested
as errors causing my build to fail:
```
...
   Linking myapp
/nix/store/22qnvg3zddkf7rbpckv676qpsc2najv9-binutils-2.43.1/bin/ld: ../.dub/cache/bindbc-sdl/2.1.0/build/dynamic-release-CgSHdJQE8_ubmp4rauoIzA/libBindBC_SDL.a(sdl.surface.o): in function `SDL_GetRGBA':
surface.d:(.text.SDL_GetRGBA+0x0): multiple definition of `SDL_GetRGBA'; ../.dub/cache/bindbc-sdl/2.1.0/build/dynamic-release-CgSHdJQE8_ubmp4rauoIzA/libBindBC_SDL.a(sdl.pixels.o):pixels.d:(.text.SDL_GetRGBA+0x0): first defined here
collect2: error: ld returned 1 exit status
Error: /nix/store/gnd8f9h2ycxrfrvrga508c4n9cxy6720-gcc-wrapper-13.3.0/bin/gcc failed with status: 1
Error /nix/store/g0k7n4bxhp43hhnxsx2m2cqaq50mwh17-ldc-1.39.0/bin/ldc2 failed with exit code 1.
````

I managed to workaround the build error on my side like so:
```
lflags "-Wl,--allow-multiple-definition" platform="linux"
```

but I prefer to fix the root cause.